version: '3'
services:
  go_blog_native:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_blog_native
    ports:
      - '8080:8080'  
    restart: on-failure
  mysql_go_blog_native:
    image: mysql:5.7
    container_name: mysql_go_blog_native
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go-blog-native
      MYSQL_USER: go
      MYSQL_PASSWORD: go
    ports:
       - 3306:3306
    restart: on-failure
